/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PointsSystem } from "./PointsSystem";
export * as factories from "./factories";
export { PointsSystem__factory } from "./factories/PointsSystem__factory";
